### ISSUE TITLE
12/20 修复对联新数据集中诗学含英的问题，初步调研python链接数据库

### ISSUE THREAD

**Issue by qsyao** [ASE-couplet/engine#1]

**Comment by Smart-Hypercube** [comment]
关于数据库：

生产环境中我们将使用 [PostgreSQL](https://www.postgresql.org/)，它的 Python 库是 [`psycopg2-binary`](http://initd.org/psycopg/)。这是我们的表结构（引擎不应该自己创建表，以下只是用表的创建语句展示表结构）：
```
CREATE TABLE Order (
    id INT PRIMARY KEY NOT NULL,
    image TEXT NOT NULL,
    tags TEXT,
    poem TEXT,
)
```
其中 `image` 字段是图片相对于 `/var/opt/poemscape/media` 的相对路径。

开发环境中，为了方便，可以使用 [SQLite](https://www.sqlite.org/)，它的 Python 库是 [sqlite3](https://docs.python.org/3/library/sqlite3.html)。用上面的语句即可创建出所需的表用于测试。

亦可使用各种 ORM 库访问数据库，我了解的比较广为使用的有 [peewee](http://docs.peewee-orm.com/) 和 [SQLAlchemy](https://www.sqlalchemy.org/)。

**Comment by Smart-Hypercube** [comment]
请参考 [SQLAlchemy 的 PostgreSQL 文档](https://docs.sqlalchemy.org/en/latest/dialects/postgresql.html)，其中 [DBAPI Support](https://docs.sqlalchemy.org/en/latest/dialects/postgresql.html#dialect-postgresql) 一节提到的接口中，我们使用 psycopg2（需 `pip install psycopg2-binary`）。

我们使用 [Unix domain socket](https://docs.sqlalchemy.org/en/latest/dialects/postgresql.html#unix-domain-connections)（而非 TCP socket）来连接数据库，用户名和数据库名都是 `poemscape`，无须密码。
