### ISSUE TITLE
`requirements.txt`

### ISSUE THREAD

**Issue by Smart-Hypercube** [ASE-couplet/engine#2]
这个仓库中尚无 `requirements.txt`，请用 `pip freeze >requirements.txt` 创建之，其中会包含所有依赖包的版本号，方便所有人在 [`venv`](https://docs.python.org/3/library/venv.html) 中使用 `pip install -r requirements.txt` 安装相同的环境，避免因环境差异导致问题。

**Comment by qsyao** [comment]
已经弄好了，等一起push
